name: ansible-aws-test-provider
description: Create file cloud-config-aws.ini in order to run ansible-test integration
inputs:
  collection_path:
    description: Path to the AWS collection to create file in.
    required: true

outputs:
  configuration_file:
    description: Cloud config ini file
    value: ${{ inputs.collection_path }}/tests/integration/cloud-config-aws.ini

runs:
  using: composite
  steps:
    - name: Set up Python '3.11'
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Create file
      run: |
        python3 ${{ github.action_path }}/create_cloud_config_file.py
      shell: bash
      env:
        ANSIBLE_TEST_CLOUD_CONFIG_FILE: "${{ inputs.collection_path }}/tests/integration/cloud-config-aws.ini"
